### ISSUE TITLE
IBC page is broken

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1449]
This is reproduced on the current main, but not reproduced on the embedded validator frontends, because they still don't have the latest registry available

<img width="700" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/de3a54c7-75ff-41d7-b05c-c15a31d60174">

```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at useChainConnector (hooks.ts:24:41)
    at IbcInForm (ibc-in-form.tsx:11:49)
    at renderWithHooks (chunk-LFUR5DFY.js?v=d73062eb:18418:26)
    at mountIndeterminateComponent (chunk-LFUR5DFY.js?v=d73062eb:21796:21)
    at beginWork (chunk-LFUR5DFY.js?v=d73062eb:22784:22)
    at HTMLUnknownElement.callCallback2 (chunk-LFUR5DFY.js?v=d73062eb:10544:22)
    at Object.invokeGuardedCallbackDev (chunk-LFUR5DFY.js?v=d73062eb:10569:24)
    at invokeGuardedCallback (chunk-LFUR5DFY.js?v=d73062eb:10603:39)
    at beginWork$1 (chunk-LFUR5DFY.js?v=d73062eb:26635:15)
    at performUnitOfWork (chunk-LFUR5DFY.js?v=d73062eb:26068:20)
```

**Comment by TalDerei** [comment]
IBC page failed to load registry

![Uploading Screenshot 2024-07-08 at 10.46.04 PM.png…]()

**Comment by turbocrime** [comment]
seems to bisect to fa798d9732654c929d167d7443c3ca788d892f88

**Comment by turbocrime** [comment]
checking out 4a31a095097d0aff292033ebbc84baf0003e75a4 and upgrading the registry alone reproduces the failure

the registry is returning an empty array for 'ibcConnections' so when `ibcChainProvider` filters the list and passes it to ChainProvider 

https://github.com/penumbra-zone/web/blob/5641af2cbd992a98bfc366d312c20f600a500b14/apps/minifront/src/components/ibc/ibc-in/chain-provider.tsx#L24-L44

which is providing chains to `useChainConnector` which asserts the presence of at least one element in that list

https://github.com/penumbra-zone/web/blob/5641af2cbd992a98bfc366d312c20f600a500b14/apps/minifront/src/components/ibc/ibc-in/hooks.ts#L21-L26

the page fails
