### ISSUE TITLE
Wasm out of memory

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#1702]
**Describe the bug**
Building a “withdraw all” transaction for a large number of auctions (about 40) leads to wasm memory overflow
```
ConnectError: [unknown] Worker ErrorEvent chrome-extension://lkpmkhpnhknhmibgnmmhdhgdilepfghe/764.js:1:80331 Uncaught RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
    at c (service-worker.js:1:311355)
    at service-worker.js:1:441479
    at async service-worker.js:1:441396
``` 

**Screenshots**
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/9e1caa5e-2745-4d54-8bad-3d9872ffc934">

**Comment by TalDerei** [comment]
auxiliary; we should remove the _serial_ build method from wasm to further reduce the binary size. 

<img width="1728" alt="Screenshot 2024-08-22 at 10 13 15 AM" src="https://github.com/user-attachments/assets/7bb85916-7e04-4fb9-b547-7d37d2b17cc6">

**Comment by TalDerei** [comment]
my initial thought is that this issue could be related to a memory leak or limited memory allocation that might need to be increased.

**Comment by TalDerei** [comment]
> auxiliary consideration; we should remove the `serial` build method from wasm to further reduce the binary size.

removing this doesn't reduce the wasm binary size (still **5 MB**), likely because dead code elimination has already taken effect during the compiler pass?
